env:
    browser: true
    es2021: true
extends:
    - google
    - plugin:@typescript-eslint/recommended
    - plugin:prettier/recommended
    - prettier
ignorePatterns:
    - examples/
    - dist/
    - tsup.config.ts
    - jest.config.ts
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: latest
    sourceType: module
    project: "./tsconfig.json"
rules:
    indent: ["error", 4]
    space-before-function-paren: ["error", "never"]
    # quotes: ["error", "single"]
    require-jsdoc: "off"
    valid-jsdoc: "off"
    "@typescript-eslint/no-explicit-any": "warn"
    max-len: "warn"
